### ISSUE TITLE
Login Endpoint Bug

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#102]
# ℹ️ Description
* Now the api/users/login endpoint expects all the fields of the user. It should expect only the username and the password.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Change the fields of the endpoint.

# Conclusion
* Write a conclusion as a comment before closing the issue.

**Comment by melihakpinar** [comment]
Merging this PR will hopefully resolve the problem.
![Example successful login response](https://github.com/bounswe/bounswe2024group10/assets/30349735/2992c02a-8dde-40c4-b806-aa9ccba7d19b)

**Comment by OguzTNCR** [comment]
Well done, thanks.
