### ISSUE TITLE
Update the Project Plan

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#114]
# ℹ️ Description
* Update the [project plan](https://github.com/bounswe/bounswe2024group10/blob/main/352.pod) from Project Libre for the milestone-2
* 352.pad will be editted
* 30 April 23.59

# 🎯 Tasks
- [x] Edit the project plan
- [x] Assign tasks to people

**Comment by NazlicanAka** [comment]
Project plan is updated, but we did not upload yet. We are waiting for [RAM](https://github.com/bounswe/bounswe2024group10/wiki/Responsibility-Assignment-Matrix) to be filled out to assign tasks to people.

**Comment by NazlicanAka** [comment]
I have updated the project plan.

**Comment by gulsensabak** [comment]
If you have put the last changes, we can close this issue.

**Comment by NazlicanAka** [comment]
I have added the new version of [project plan](https://github.com/bounswe/bounswe2024group10/wiki/Project-Plan) to both file and screenshoots.
