### ISSUE TITLE
Adding responsibilities to RAM

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#115]
# ℹ️ Description
* We need to update the RAM before the [Milestone-2](https://github.com/bounswe/bounswe2024group10/milestones)
* We will update the our previous ram, please review it, and if necessary add tasks.
* Due date: 30 April 5 pm.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Add responsibilities
- [x] Fill out the table 
- [x] Ali Bartu
- [x] Nazlıcan
- [x] Gülşen
- [x] Melih
- [x] Yasin
- [x] Oğuzhan
- [x] Hüseyin
- [x] Yusuf Kağan
- [x] Onur
- [x] Ömer Faruk

# Conclusion
* will be filled

**Comment by NazlicanAka** [comment]
@gulsensabak and I have created [RAM,](https://github.com/bounswe/bounswe2024group10/wiki/Responsibility-Assignment-Matrix) make some changes and arrangements. Please, do not forget to fill out your responsibilities.

**Comment by OmerFarukBOUN** [comment]
Can you change the backend section?
I think it does not make a good job dividing it.
I am not sure but initializing Classes, implementing endpoints and initializing docker would be better for dividing jobs. What do you think @melihakpinar @Pqrq @SturmR  ?

**Comment by OguzTNCR** [comment]
I think we should divide the web part into subtasks:
* Navbar implementation
* Login Page implementation
* Profile Page implementation
* Post Card component implementation
* Post Detail Page implementation
* Search Page implementation
* Endpoint connections

**Comment by NazlicanAka** [comment]
Thanks for your comments, I am adding your tasks to RAM.

**Comment by gulsensabak** [comment]
Can you add these ones for mobile part in ram @NazlicanAka?
Main Screen
Settings Screen
Search Screen
Home Screen
MyProfile Screen
Post Screen
Login Screen
Sign-Up Screen
GuestUser Home Screen
GuestUser Search Screen

**Comment by gulsensabak** [comment]
Can you also add this screen: Search Results Screen @NazlicanAka?

**Comment by NazlicanAka** [comment]
I have added your suggestions, please fill out the RAM.

**Comment by NazlicanAka** [comment]
All team members are filled out the RAM.
