### ISSUE TITLE
Implementing and designing the search function 

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#123]
# ℹ️ Description
The basic functionality of the search is done and the frontend team is currently working on the design. However, the search function currently only displays some data it can find about the animal in the input. We should try adding more possible queries to it. For example, it should give information about the animals living in a certain location. We should write our ideas in the comments.
# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Basic search implementation
- [ ] Designing 
- [ ] More ideas for queries

# Conclusion
...

**Comment by NazlicanAka** [comment]
@bartukonca can you give example about basic search implementation to facilitate learning for us. I do not know really, but I can help if you can give more information about tasks

**Comment by bartukonca** [comment]
You can check out this page for information on how to write the queries for Wikidata.  https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial Currently the query we have isn't perfect, we can work on improving it to find the related animals better.
Later we can also add queries for finding a list of animals with certain properties. For example their diel cycle, or their taxonomy.

**Comment by Pqrq** [comment]
Mobile search is currently implemented.

Can one update the status of this issue?

**Comment by bartukonca** [comment]
The basic functionality, searching an animal and getting some data, works. However, sometimes it can show irrevelent animals, which we are trying to fix. Also other queries can be written, which I will also research, to search for locations or properties etc.

**Comment by gulsensabak** [comment]
I think we are getting intended results at least for that milestone. Should we close this issue?

**Comment by bartukonca** [comment]
Okay we can close it.
