### ISSUE TITLE
Solving the Android Network Error

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#125]
# ℹ️ Description
* We are getting Android Network Error in mobile part. We are trying to fix it so that our mobile application works correctly.
* 

# 🎯 Tasks
* Solve the bug

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
I think, the android network error is solved. If it is, I will close this issue. Can you check it please @Pqrq ?

**Comment by Pqrq** [comment]
Yes, the android network error is currently solved.

Solution Method: 
* Changed "localhost" with "10.0.2.2" 
* Removed HTTPS requests in our code

As there is nothing more to be done about this issue, I am closing it.
