### ISSUE TITLE
Fixing searches for mobile 

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#126]
# ℹ️ Description
* In demo, we have faced an error for search bar in mobile part. We will fix it and upload it to the github until  30th of April- 10pm

# 🎯 Tasks
* fix the error in search bar

# Conclusion
* will be filled

**Comment by Pqrq** [comment]
I have fixed the error occuring in the search bar. Now it can search for items with the given searchText.

Only showing the results is left. I will inform once it is done.

**Comment by Pqrq** [comment]
I have completed the "showing the search results" part. The last codes are currently in mobile-main branch.

Can you review the codes @gulsensabak

**Comment by gulsensabak** [comment]
I have reviewed all of the codes. Thanks for your effort. I am closing this issue right now.
