### ISSUE TITLE
Adding Build & Install Instructions to README 

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#127]
# ℹ️ Description
* Add building and installing instructions to the README file
* Theme: Documentation
* Files to Change: README.md
* Estimation: 30.04.2024, Time: 22.00

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Write the instructions for how to build our application to the README file
- [ ] Write the instructions for how to install our application to the README file

**Comment by karatashsyn** [comment]
We have added the necessary instructions  to the readme.md file with @gulsensabak  and @Pqrq related to building and running the applications
