### ISSUE TITLE
Web App Deployment

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#132]
# ℹ️ Description
React web app should be deployed to Digitial Ocean

# 🎯 Tasks
- [ ] Write Dockerfile
- [ ] Deploy the Docker image to digital ocean.

**Comment by gulsensabak** [comment]
I think, we handled this issue. If I am not wrong, we can close this issue. @karatashsyn @OguzTNCR

**Comment by OguzTNCR** [comment]
We solved it with the help of @melihakpinar.
