### ISSUE TITLE
Document Front End Team Meeting notes

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#140]
# ℹ️ Description
Documenting  notes of the Front end Team meeting held on 9 May.

# 🎯 Tasks
- [x] Documenting what we have talked
- [x] Documenting participants

**Comment by NazlicanAka** [comment]
I have added the meeting notes, can you review @OguzTNCR?

**Comment by NazlicanAka** [comment]
I am closing this, I have added and oğuzhan has reviewed.
