### ISSUE TITLE
Create Milestone-3

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#141]
# ℹ️ Description
* to keep track of our issues and our progress, we need to connect our issues to milestone-3

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] create milestone-3
- [ ] connect related issues with milestone-3

**Comment by gulsensabak** [comment]
I have connected the related issues to Milestone3 so I have added myself to assignees. If you are available we can also put a new issue to update RAM and Project Plan. @NazlicanAka

**Comment by NazlicanAka** [comment]
Thanks Gülşen. I am closing this issue because we have already created project plan and RAM issues.
