### ISSUE TITLE
Preparing create post screen for mobile

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#147]
# ℹ️ Description
* In mobile app, user shall be able to create posts. Because of this requirement, we have to design create post screen. 

# 🎯 Tasks
- [x] prepare create post screen

# Conclusion
* will be filled

**Comment by TheRealLowyer** [comment]
I created the screen. However, constant responses will be created for backend services.

**Comment by gulsensabak** [comment]
I think we have an issue for that addition. That's why, we can close that issue.
