### ISSUE TITLE
Create posts and users for the demo

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#148]
# ℹ️ Description
We need to create various well structured users, posts, preferebly comments as well, which capture the essence of the app for the demo/presentation.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Create users.
- [ ] Create posts.
- [ ] Create comments.

# Conclusion
...

**Comment by gulsensabak** [comment]
If you need help, you can assign this to me too. @bartukonca

**Comment by OmerFarukBOUN** [comment]
I think this is a one big task, it does not need to be partitioned. Since we need to generate random graph for it.

**Comment by gulsensabak** [comment]
Okay, then I wish you good work.
