### ISSUE TITLE
Write user tests

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#151]
# ℹ️ Description
* We should write user tests to test our application and web site.

# 🎯 Tasks
- [x] Write user test

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
I wrote one of these user tests. I will add the other test cases also. If you are available, can you review the cases that I have created today? @bartukonca

**Comment by gulsensabak** [comment]
I completed user tests. I will add them to the side bar as a page. You can review from there. @bartukonca

**Comment by bartukonca** [comment]
Yes I have reviewed them and fixed minor typos in the process. Other than that there is no problem. I am closing this issue.
