### ISSUE TITLE
Create User Profile Screen for Mobile

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#157]
# ℹ️ Description
* We need to create user profile screen to use in mobile app.

# 🎯 Tasks
- [x] User Profile Screen

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
I have created the pull request for last changes. I have also changed the bottom bar. I am waiting your reviews. @Pqrq @TheRealLowyer

**Comment by TheRealLowyer** [comment]
I reviewed your merge pull request. There was some conflicts due to base branch. I changed the base branch and fixed the issue. Your pages seems good. Keep up with the good work :)

**Comment by gulsensabak** [comment]
Thanks for fixing the issue and reviewing. I am closing this issue.
