### ISSUE TITLE
Service response constants creation for the mobile app

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#167]
# ℹ️ Description
* Service response constants creation for the mobile app
* 16.05.2024

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Service reponse constants
- [ ] 

# Conclusion
* Write a conclusion as a comment before closing the issue.

**Comment by gulsensabak** [comment]
I think, we handled the creation of all service response constants. After reviewing, we can close this issue. @TheRealLowyer
