### ISSUE TITLE
Feed ( Home ) page

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#174]
# ℹ️ Description
User spesific feed will be displayed on homepage.
# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [ ] Feed will be fetched from backend.
- [ ] Results will be rendered on the home page

**Comment by OguzTNCR** [comment]
Feed fetched using posts/getFeed endpoint and rendered in the home page.
