### ISSUE TITLE
Creating the milestone-3 report

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#194]
# ℹ️ Description
We have to create the report by the end of the day, everyone will fill their own sections. I will work on the executive summary part of the report, however I need help with the following sections -> Deployment, APK of the mobile app, the status of the requirements(are they implemented, partially implemented or not implemented), tagged release

# 🎯 Tasks

# Conclusion

**Comment by Pqrq** [comment]
As the report is successfully written and submitted, I am closing this issue.
