### ISSUE TITLE
Project Plan and RAM Review

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#196]
# ℹ️ Description
* I have uploaded the new project plan. Herse is the [link](https://github.com/bounswe/bounswe2024group10/blob/main/352_3.pod).  
* Also the RAM is created, please fill out the new added fields. 
* if you want to add something to RAM or in the project plan, or change you can leave a comment under this issue, I will fix it.

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] RAM fill filled by every member

**Comment by gulsensabak** [comment]
I think this issue is done so I am closing this issue.
