### ISSUE TITLE
Documenting First Lab Report

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#201]
# ℹ️ Description
* Since we are in the first lab we should write the lab report.

# 🎯 Tasks
- [ ] Writing lab report

**Comment by Pqrq** [comment]
The report has been completed, and also revised by Nazlıcan, thanks a lot. (see. [Lab report revision issue](https://github.com/bounswe/bounswe2024group10/issues/205)

I am closing this issue as there is nothing else to be done.
