### ISSUE TITLE
Creating a Communication Plan and General Plan

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#204]
# ℹ️ Description
* As we are starting our new project, we need to create a new communication plan and establish a new general plan

# 🎯 Tasks
- [x] Discuss and decide on a communication plan
- [x] Discuss and decide on a general plan

**Comment by NazlicanAka** [comment]
Communication plan is determined according to free time of team members. Also, added to the repo as [communication plan](https://github.com/bounswe/bounswe2024group10/wiki/Communication-Plan)
