### ISSUE TITLE
Document second lab report

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#217]
# ℹ️ Description
* Since we are in the second lab we should write the lab report.

# 🎯 Tasks
- [x] Write lab report

**Comment by karatashsyn** [comment]
Documented the [lab report](https://github.com/bounswe/bounswe2024group10/wiki/Cmpe451-Week-2-Lab-Report). @SturmR Can you please review the report

**Comment by SturmR** [comment]
LGTM.
