### ISSUE TITLE
Community Feature Enhancement

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#225]
Community Features will determine our requirements. In order to write our requirements we need appropriate community features.
The deadline of the task is Sunday night.
# 🎯 Tasks
- [x] Write the bare-bones of community features.

**Comment by OmerFarukBOUN** [comment]
I have written the [draft of the forum ](https://github.com/bounswe/bounswe2024group10/wiki/Draft-of-Forum). There are some empty places. It can be advanced more. Feel free to update it :)
