### ISSUE TITLE
Create a glossary for our project requirements 

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#227]
# ℹ️ Description
The task is to create a glossary section for the Requirements Page. This glossary will provide definitions and explanations of specific terms, roles, and features to improve clarity and ensure consistency throughout the documentation

# 🎯 Tasks
- [x] Develop a glossary that defines key terms related to the functional and non-functional requirements of the project, which
will be included at the beginning of the Requirements Page.

**Comment by TheRealLowyer** [comment]
Created the glossary section which includes the words in requirement topics that discussed both in lab and meeting that held on Friday. @gulsensabak Could you please review the work done for further explanation of the words?

**Comment by gulsensabak** [comment]
I have reviewed the glossary part. It is so good but we have to clarify some parts in our project. (like how many user type we will create) I will review again after this decision process.
