### ISSUE TITLE
Rearrange Requirements and Divide into Subsequent Sections

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#228]
# ℹ️ Description
The objective of this task is to restructure the existing requirements documentation to improve readability and logical flow. This involves rearranging the requirements, grouping related items together, and dividing them into clear, sequential sections. The revised layout should ensure that the requirements are easily understandable and that similar functionalities are grouped under relevant categories.

# 🎯 Tasks
- [x] Organize the requirements into logical sections, making it easier for stakeholders to navigate and reference.
- [x] Create a numbered format that clearly distinguishes between high-level categories (e.g., Functional Requirements, Non-Functional Requirements) and specific subcategories (e.g., User Registration, Forum Topics).

**Comment by TheRealLowyer** [comment]
I rearranged the requirements to refer easily when dealing with the mock-up scenarios. Also, I added the additional requirements that discussed in the lab section. @Pqrq Could you please review the work done for further documention ideas?

**Comment by Pqrq** [comment]
I have started revising the requirements part, however it seems like there are too many subtasks related to revising, so I will explain them in another issue which I will open soon.
