### ISSUE TITLE
Consult about 'Feature Based on Moderation'

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#230]
# ℹ️ Description
We couldn't decide whether our app should have 4 types of user of 2 types of user. We should consult and ask we it will be too simple to have 2 types of user.

# 🎯 Tasks
- [x] Consult to the TA.

**Comment by OmerFarukBOUN** [comment]
We have had asked about it and he said we need to keep the 4 user types and add a unregistered user type.
