### ISSUE TITLE
Correct User & System Requirements

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#234]
# ℹ️ Description
Some of our requirements should be user requirements rather than system requirements. Fix these reqirements

# 🎯 Tasks
- [x] Distinguish user and system requirements
- [x] Do the appropriate changes in our ["Requirements"](https://github.com/bounswe/bounswe2024group10/wiki/Requirements) document.

**Comment by TheRealLowyer** [comment]
We did the appropriate changes and got the review of the advisor TA and further revision has made.
