### ISSUE TITLE
Create Database Diagram

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#235]
# ℹ️ Description
In order to create our database properly, we need to create a database diagram.

# 🎯 Tasks
- [ ] Create the database diagram
- [ ] Put the diagram into our Wiki page, where it should be easily visible

**Comment by NazlicanAka** [comment]
Did you create diagram, do you need help for that issue, I can help you.

**Comment by OmerFarukBOUN** [comment]
I have created the diagram but it needs to be updated, since while I was sick there were some changes. The new diagram will be available soon.

**Comment by OmerFarukBOUN** [comment]
Since db diagram is currently redundant, I am closing the issue. [Current diagram](https://drawsql.app/teams/bruh-55/diagrams/cmpe451) is a bit outdated. This can be used, if needed.
