### ISSUE TITLE
Third Lab Reporting

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#236]
- Write the lab report and upload to the wiki page.

**Comment by Pqrq** [comment]
Can you edit the issue according to our template please?

**Comment by Pqrq** [comment]
I have written the report for our 3rd Lab.

[Here](https://github.com/bounswe/bounswe2024group10/wiki/Cmpe451-Week-3-Lab-Report) is the link.

As there is nothing more to be done here, I am closing this issue.
