### ISSUE TITLE
Research UI templates

### ISSUE THREAD

**Issue by SturmR** [bounswe/bounswe2024group10#237]
# ℹ️ Description
Explore different variations of UI on the web that we can use in our app. 

# 🎯 Tasks
- [ ] Discuss what sort of UI would suit our project and draw inspiration from templates across the web.

**Comment by Pqrq** [comment]
Can you edit the issue according to our template please?

**Comment by SturmR** [comment]
Edited issue according to template.

**Comment by karatashsyn** [comment]
Research is done and I (@karatashsyn ) will be the one who will create all the design for mobile. Design is still on process and its features can be also applied to web design later.
