### ISSUE TITLE
Fill the Mock-ups page 

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#238]
ℹ️ Description
Mock-ups should be done in a week. Please write your mock-ups to the page I have created. Please create your mock-ups according to requirements. Here is the [link](https://github.com/bounswe/bounswe2024group10/wiki/Mock%E2%80%90Ups).

🎯 Tasks
- [ ] Create a mock-up according to scenario.

**Comment by Pqrq** [comment]
Can you edit the issue according to our template please?

**Comment by NazlicanAka** [comment]
I have updated my issue according to the issue template, thanks.

**Comment by NazlicanAka** [comment]
there are enough mock-ups, so I am closing this issue.
