### ISSUE TITLE
Edit meeting notes 22/02

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#24]
I will fix the meeting notes according to the template we have made. I will add the attendees, a table for action items and deadlines.

**Comment by NazlicanAka** [comment]
Hi Bartu, will you edit the last meeting notes according to template?

**Comment by bartukonca** [comment]
Yes, I will fix the last one and the ones before that according to the template, if I have difficulties I might post another issue with the label help wanted.

**Comment by bartukonca** [comment]
I have updated them and made some minor changes to the template as well. If anyone has something they don't like or they have better ideas they can feel free to make some changes.
