### ISSUE TITLE
Revising Lab Report

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#242]
# ℹ️ Description
We need to revise our [Lab Report](https://github.com/bounswe/bounswe2024group10/wiki/Cmpe451-Week-3-Lab-Report)

# 🎯 Tasks
- [x] Revise our lab report
- [x] Add required parts (standards, etc.)

**Comment by TheRealLowyer** [comment]
I added W3S Web annotation standarts and requirements under Non-functional requirements part. Also, revised the specific parts (2.3.4 / 1.1.1.1.2.2. /  1.1.1.9. ) in requirements. Further, I clearly stated the difference between user,registered user and admin in the glossary.

**Comment by gulsensabak** [comment]
I have revised the remaining part for functional and non functional requirements part. I think they are so clear right now. If you have same idea with me, we can close this issue.
