### ISSUE TITLE
Creating Mockup Screens for Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#243]
# ℹ️ Description
Mockups for the mobile applications screens must be created. This will be handled on Sunday 13.10.2024 by mobile development team.

# 🎯 Tasks
- [ ] Create Mockup Screen sketches for mobile application.

**Comment by gulsensabak** [comment]
We have created 24 different screens for mobile. If you want, we can close this issue.

**Comment by karatashsyn** [comment]
Let's discuss the final results with the all team in the following lab on 15.10.2024 before closing the issue. @gulsensabak @Pqrq

**Comment by gulsensabak** [comment]
We have discussed and finalized this topic, so I am closing this isue.
