### ISSUE TITLE
Document Mobile Meeting Notes

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#244]
# ℹ️ Description
We need to document our first meeting as mobile group.

# 🎯 Tasks
- [x] Document first mobile meeting notes.
- [x] Store it under a new wiki folder named Mobile Team Meetings

**Comment by karatashsyn** [comment]
All discussed topics are documented on the page you have created. Thank you for your work. Can you also please give a link to the related wiki page

**Comment by gulsensabak** [comment]
I have put the link of the related wiki page to the sidebar. I think it is okay right now. If it is okay, can you close this issue? @karatashsyn
