### ISSUE TITLE
Open the project for this semester

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#245]
# ℹ️ Description
We need to have a project from Projects part. We need to open the project to keep track of our works.

# 🎯 Tasks
- [x] Open the project

**Comment by Pqrq** [comment]
I have opened this semester's CMPE451 project.

[Here](https://github.com/orgs/bounswe/projects/79) is the link.

As there is nothing more to be done, I am closing this issue.
