### ISSUE TITLE
Upload the Mock Screens to wiki

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#247]
# ℹ️ Description
As mockups for the mobile applications screens has been created. Upload these Mockups to the wiki page

# 🎯 Tasks
- [x] Upload mockups for mobile application

**Comment by Pqrq** [comment]
I have added our sketch mockups to [mockups page](https://github.com/bounswe/bounswe2024group10/wiki/Mock%E2%80%90Ups). 

I am closing this issue accordingly.
