### ISSUE TITLE
Create Class Diagrams

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#254]
# ℹ️ Description
We need to create Create class diagrams for our forum as the backend team

# 🎯 Tasks
- [ ] Create our class diagrams

**Comment by Pqrq** [comment]
I did some edits at the issue.

**Comment by melihakpinar** [comment]
Done.

https://github.com/bounswe/bounswe2024group10/wiki/Tradeverse-Class-Diagram
