### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#255]
# ℹ️ Description
We need to create our sequence diagrams for our application

# 🎯 Tasks
- [ ] Revise our old sequence diagrams
- [ ] Create our new sequence diagrams

**Comment by gulsensabak** [comment]
We have created the sequence diagrams related to our project on the lab. That's why, I am closing this issue. If you have any questions about sequence diagrams, you can reopen this issue.
