### ISSUE TITLE
Modify Requirements According to user tags

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#257]
# ℹ️ Description
While reviewing the requirements, me and Melih noticed that we have not add the user tag that we have written in [Communication Features](https://github.com/bounswe/bounswe2024group10/wiki/Community-Features). 

# 🎯 Tasks
- [x] Add user tags in glossary.
- [x] Add necessary requirements about user tags.

**Comment by Pqrq** [comment]
Edited the issue according to the template.

**Comment by NazlicanAka** [comment]
Tags are written to the requirements.
