### ISSUE TITLE
Discuss on semantics aspect of the project

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#259]
# ℹ️ Description
We need to discuss semantic aspect of the project. What kind of parameters will be play role on the semantic search results. Additionally, discuss the way how post contents are going to obtain the tags. 

# 🎯 Tasks
- [ ] Discuss the semantic search strategy.
- [ ] Discuss the method of assigning tags to the posts.

**Comment by gulsensabak** [comment]
We have discussed and decided the semantic search strategy. Also we have decided the method of assigning tags to the posts. That's why, I am closing this issue right now. If you are not satisfied from the decisions, you can reopen this issue. We can meet and talk about your aspect.
