### ISSUE TITLE
Research on topics about the incoming project

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#26]
We should all start our research on the following topics and discuss what we know in the upcoming meeting.

- [x] #42
- [x] Linked Data
- [x] SPARQL semantic queries
- [x] Wikidata API
- [x] Mobile application development
- [x] Web application development
- [x]  Application Programming Interface (API) use and development

**Comment by NazlicanAka** [comment]
I have added my research about SPARQL.
