### ISSUE TITLE
Create User Welcoming Screen for Mobile

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#271]
# ℹ️ Description
* We need to create user welcoming screen to use in mobile app.

# 🎯 Tasks
- [x] User Welcoming Screen 1 which asks user for a profile photo.
- [x] User Welcoming Screen 2 which asks user to choose an experience level with finance.

**Comment by karatashsyn** [comment]
Screens are created and presented right after register
