### ISSUE TITLE
Create "Create" Screen

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#279]
# ℹ️ Description
* We need to create "Create" screen to use in mobile app.

# 🎯 Tasks
- [ ] "Create" screen

**Comment by gulsensabak** [comment]
Can we change the title of the issue? It isnot clear I think. Maybe we can do it as Create Subforum/Post Screen.

**Comment by gulsensabak** [comment]
Since we put the same screen name to the pull request, I will not update teh title of that issue. The related pull request for that screen is [here](https://github.com/bounswe/bounswe2024group10/pull/297)
