### ISSUE TITLE
Create "Followed Subtopics" Screen

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#282]
# ℹ️ Description
* We need to create "Followed Subtopics" screen to use in mobile app.

# 🎯 Tasks
- [ ] "Followed Subtopics" screen

**Comment by gulsensabak** [comment]
I have created the followed subtopics/ tags screen for mobile. You can reach the related pull request from [here](https://github.com/bounswe/bounswe2024group10/pull/312)
