### ISSUE TITLE
Create "Add Portfolio Asset" Screen 

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#283]
# ℹ️ Description
* We need to create "Add Portfolio Asset" screen to use in mobile app.

# 🎯 Tasks
- [ ] "Add Portfolio Asset" screen

**Comment by gulsensabak** [comment]
I have created add portfolio asset screen for mobile. You can reach the related pull request from [here](https://github.com/bounswe/bounswe2024group10/pull/301)
