### ISSUE TITLE
Create "Search Results" Screen

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#284]
# ℹ️ Description
* We need to create "Search Results" screen to use in mobile app.

# 🎯 Tasks
- [x] "Search Results" screen

**Comment by Pqrq** [comment]
Divided the issue as two issues

**Comment by karatashsyn** [comment]
Updated the assignee since there was a misunderstanding while assigning screens.

**Comment by karatashsyn** [comment]
Created Search Results screen and merged into mobile-main with [PR295](https://github.com/bounswe/bounswe2024group10/pull/295)
