### ISSUE TITLE
Set up eslint and prettier files 

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#287]
# ℹ️ Description
*  Throughout the project, prettier and eslint files were installed as linter and code organizer to follow the right standards, keep the code clean and make it easier to spot bugs in the code.

# 🎯 Tasks
- [x] Set up eslint and prettier files

**Comment by karatashsyn** [comment]
Eslint and Prettier has been set up for the project and merged into mobile-main with [#PR349](https://github.com/bounswe/bounswe2024group10/pull/349)
