### ISSUE TITLE
Create Portfolio Screen for Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#289]
# ℹ️ Description
* We need to create portfolio screen in mobile app.

# 🎯 Tasks
- [x] Create a portfolio screen in which authenticated user can see his / her portfolio assets.
- [x] Add current total value of the user's assets into this page.

**Comment by Pqrq** [comment]
I have created the "Portfolio" Screen. 

See the [related PR](https://github.com/bounswe/bounswe2024group10/pull/313)

I am closing this issue accordingly.
