### ISSUE TITLE
Create Login & Register Pages for Web

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#304]
ℹ️ Description
* Develop UI pages for user login and registration with form validation and proper token handling.

🎯 Tasks
- [x] Design and implement login page UI.
- [x] Design and implement registration page UI.
- [x] Add form validation for email and password inputs.
- [x] Send login/registration data to backend API.
- [x] Store received JWT token in localStorage upon successful login or registration.

**Comment by TheRealLowyer** [comment]
The login and signup components has been successfully developed and integrated. The ui is consistent with our design guidelines, ensuring an intuitive and engaging user experience.
