### ISSUE TITLE
Forum Components

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#305]
ℹ️ Description
* Break down the forum structure into reusable components such as Post, Comments, and Sorting. 

🎯 Tasks
- [x] Create a reusable Post component that renders post details (description, like/dislike counts, comments, etc.).

**Comment by TheRealLowyer** [comment]
The forum component has been successfully developed and integrated. The ui is consistent with our design guidelines, ensuring an intuitive and engaging user experience.
