### ISSUE TITLE
Implement Routing

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#306]
ℹ️ Description 
* Set up the React Router DOM to manage the navigation between different pages of the application.
🎯 Tasks
- [ ] Set up React Router DOM for page navigation.
- [ ] Implement protected routes for Subforum and Profile pages.
- [ ] Define routes for /login, /register, /subforums/:forumName, and /Home.
- [ ] Ensure unauthenticated users are redirected to the login page when attempting to access protected routes.

**Comment by TheRealLowyer** [comment]
The routing implementation is now complete, and all routes have been tested to ensure smooth navigation throughout the application.
