### ISSUE TITLE
Implement validate-token Endpoint

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#307]
ℹ️ Description
* Add a backend API endpoint /api/validate-token to check the validity of JWT tokens. This endpoint will be called by the frontend to verify the token’s status and, if valid, return the user’s details.

🎯 Tasks
- [ ] Create the /api/validate-token endpoint in the backend.
- [ ] Check if the JWT token exists and is valid (not expired or tampered with).
- [ ] Return user details if the token is valid.
- [ ] Handle invalid tokens by logging the user out and returning an appropriate response.
- [ ] Integrate this validation process with the AuthWrapper on the frontend.

**Comment by melihakpinar** [comment]
Done. See #268
