### ISSUE TITLE
Use the Favourite Repository Template

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#32]
Created a [Favourite Repository Template](https://github.com/bounswe/bounswe2024group10/wiki/Favourite-Repository-Template). Apply it for your favourite repository in the [Favourite Repositories ](https://github.com/bounswe/bounswe2024group10/wiki/Favourite-Repositories) page.

- [x] Nazlıcan Aka
- [x] Mesut Melih Akpınar
- [x] Yasin Atlı
- [x] Yusuf Kağan Çiçekdağ
- [x] Ömer Faruk Erzurumluoğlu
- [ ] Onu Kafkas
- [x] Hüseyin Karataş
- [x] Ali Bartu Konca
- [x] Gülşen Şabak
- [ ] Cem Sarpkaya
- [ ] Oğuzhan Tuncer

**Comment by karatashsyn** [comment]
I applied this template for my favourite repository.

**Comment by uskudarli** [comment]
I can't follow what this issue is meant to describe. Also, it is unclear what the reassignments and comments. Be careful about clearly articulating the tasks and updates.

**Comment by Pqrq** [comment]
Changed the title, as it was too long.

**Comment by karatashsyn** [comment]
> Changed the title, as it was too long.

I think we should update is as use the template or apply template since it is already created by @OguzTNCR

**Comment by Pqrq** [comment]
I have updated my favourite repository page -according to our template- as well

**Comment by bartukonca** [comment]
I have also updated my page.

**Comment by gulsensabak** [comment]
I fitted my favourite repository into the template

**Comment by TheRealLowyer** [comment]
I updated my page accordingly.

**Comment by NazlicanAka** [comment]
I have update my fav repo according to [fav repo template] (https://github.com/bounswe/bounswe2024group10/wiki/Favourite-Repository-Template)
