### ISSUE TITLE
 Add user details endpoints

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#328]
ℹ️ Description
This issue involves adding a new field for the user's bio in the User model and implementing two new endpoints: GetUserDetails and EditUserDetails. Users will be able to edit their email, profile picture, bio, and tag through these endpoints.

🎯 Tasks
- [x] Add a bio field to the User model.
- [x] Implement the GetUserDetails endpoint to retrieve user information.
After 1st milestone:
- [x] Move get-user-details endpoint from /api/auth to /api/user.
- [x] Change request type of  get-user-details from POST to GET.
- [x] Implement the set-user-details endpoint to allow users to update their email, profile picture, bio, and tag.

**Comment by melihakpinar** [comment]
Completed the first 2 tasks. See #329

**Comment by melihakpinar** [comment]
I am leaving this issue to @NazlicanAka

**Comment by NazlicanAka** [comment]
I have completed the tasks, and merge the code to the main [see](https://github.com/bounswe/bounswe2024group10/pull/350).
