### ISSUE TITLE
Add Missing Parts to the RAM

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#337]
ℹ️ Description
I am writing the RAM. But, there will be some missing parts in the RAM. Can you add the parts that you think is missing.

🎯 Tasks
- [x] Teammates write missing parts as a comments of this issue.
- [x] Add the new parts to the RAM.

**Comment by NazlicanAka** [comment]
I have created the [RAM](https://github.com/bounswe/bounswe2024group10/wiki/Responsibility-Assignment-Matrix-Tradeverse).

**Comment by TheRealLowyer** [comment]
I added the missing parts related to web in the RAM.

**Comment by NazlicanAka** [comment]
Don' t forget to fill up RAM until 5 pm today.

**Comment by OguzTNCR** [comment]
I completed my parts.

**Comment by NazlicanAka** [comment]
We have delivered the RAM for the milestone-1. [see](https://github.com/bounswe/bounswe2024group10/wiki/Responsibility-Assignment-Matrix-Tradeverse)
