### ISSUE TITLE
Write Milestone-1 Report 

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#338]
ℹ️ Description
Yasin, Ömer Faruk, and I made a meeting to separate parts of the milestone-1 report. 

🎯 Tasks
- [x] RAM
- [x] Project plan
- [x] A summary of the customer feedback and reflections.
- [x] The requirements addressed in this milestone.

**Comment by NazlicanAka** [comment]
I have created the RAM, [link](https://github.com/bounswe/bounswe2024group10/wiki/Responsibility-Assignment-Matrix-Tradeverse).

**Comment by NazlicanAka** [comment]
I have created the project plan, with dates and assignees. See of the page with sceenshots [link], the committed code [link](https://github.com/bounswe/bounswe2024group10/blob/main/Tradeverse-App%20Project%20Plan.pod)

**Comment by OmerFarukBOUN** [comment]
Finished it, closing the issue.
