### ISSUE TITLE
Create the mockups

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#34]
# ℹ️ Description
* We need to finish the mockups by saturday, you should assign certain parts to each other, when said parts are done send them to the group for us to validate, then we can upload them. 

# 🎯 Tasks
- [x] Create the mockups
- [x] Send them to the group to validate
- [x] Upload them

**Comment by TheRealLowyer** [comment]
Mobile scenario mockups and basic mockups added.

**Comment by OguzTNCR** [comment]
For desktop user page, feed page, login, sign up, feed-comment added. Also size of the images standardized.
