### ISSUE TITLE
Document the determined standard

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#351]
ℹ️ Description 
* We have determined the w3c standard that we are going to use in our project.  We are going to do the first task that is assigned in the lab5. 
* What is it for, its benefits?
🎯 Tasks
- [x] Document what is this standart for, its benefits.

**Comment by NazlicanAka** [comment]
All documented, [see](https://github.com/bounswe/bounswe2024group10/wiki/W3C-Standard-%E2%80%90-Annotation).
