### ISSUE TITLE
Document what are the requirements of the determined standard

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#352]
ℹ️ Description 
* We have determined the w3c standard that we are going to use in our project.  Assignees are going to do the second task that is assigned in the lab5. 
* What are the requirements of the determined standard?

🎯 Tasks
- [ ] Document what are the requirements of the determined standard

**Comment by Pqrq** [comment]
We have documented the requirements for our decided standard. Here is the [related link](https://github.com/bounswe/bounswe2024group10/wiki/W3C-Standard-%E2%80%90-Annotation)

As our task is done, I am closing this issue.
