### ISSUE TITLE
Create User Group Story 1

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#355]
ℹ️ Description 
* For our Lab 6, we need to create some user stories. These stories includes some extra information like specific location, time, duration. The users need not have names, images, etc; but they should have specific demographics. It's not a single people person but a group of people with similar characteristics regarding the user story.

🎯 Tasks
- [x] Create a user story according to these above criterias.

**Comment by karatashsyn** [comment]
Done, documented [here](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-1)
