### ISSUE TITLE
Meet and distribute backend tasks

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#359]
ℹ️ Description 
We have some tasks like portfolio mechanics, Yahoo finance API connection, and endpoints related to tasks, comments, annotation. We should discuss about how will we distribute the tasks.
🎯 Tasks
- [x] Design "W3C Standard - Annotation"
- [x] Discuss what will be done.
- [x] Share the tasks

**Comment by melihakpinar** [comment]
I will deal with the Yahoo Finance endpoints.

**Comment by NazlicanAka** [comment]
I will deal with the task related to portfolio endpoints. See related [issue](https://github.com/bounswe/bounswe2024group10/issues/360).
