### ISSUE TITLE
Implement portfolio endpoints

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#360]
ℹ️ Description 
We should implement endpoints related to portfolio. Users should be able to share their portfolio, change the visibility, add new assets and delete them, and get other users' portfolios.

🎯 Tasks
- [x] Design portfolio database and create Portfolio model.
- [ ] Implement /api/portfolio controllers.
- [ ] Implement the logic.
- [ ] Test the endpoints.

**Comment by NazlicanAka** [comment]
Design portfolio database and create Portfolio model is done, PR is created waited for review, [see](https://github.com/bounswe/bounswe2024group10/pull/387).
