### ISSUE TITLE
Implement posts, comments, annotation

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#362]
ℹ️ Description 
We should implement endpoints related to content. Users should be able to share posts, make comments, etc. Implement mentioning about any other content in the forum since we are sticking with the [W3C Standard - Annotation](https://github.com/bounswe/bounswe2024group10/wiki/W3C-Standard-%E2%80%90-Annotation).

🎯 Tasks
- [x] Design related databases.
- [ ] Implement controllers.
- [ ] Implement the logic.
- [ ] Test the endpoints.

**Comment by OmerFarukBOUN** [comment]
Annotation standard will be implemented in Milestone-3, everything else was implemented
