### ISSUE TITLE
Place UI Designs Into Group Story Documents

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#366]
ℹ️ Description 
* For our Lab 6, we created 2 user group stories. These documents also need the mentioned features' related ui designs.

🎯 Tasks
- [x] Put the related mobile ui screens into the scenario documents [Group 1 Scenario](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-1) and [Group 2 Scenario](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-2)

**Comment by Pqrq** [comment]
I have added the related mobile screens. Related links for [Group Scneario 1](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-1#related-mobile-mockups) and [Group Scneario 2](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-2#related-mobile-mockups) are here.

I am closing this issue accordingly.
