### ISSUE TITLE
Web - Create Sidebar

### ISSUE THREAD

**Issue by SturmR** [bounswe/bounswe2024group10#369]
ℹ️ Description 
* A sidebar should be implemented from scratch. This sidebar will be equivalent to the bottom bar on our mobile page.

🎯 Tasks
- [x] Create sidebar.
- [x] Create the necessary buttons for the sidebar such as account, search, etc.
- [x] Implement functionality such that sidebar widens when clicked on.

**Comment by OguzTNCR** [comment]
The sidebar is added to the main layout. It can be used for the navigation.
