### ISSUE TITLE
Web - Account Page

### ISSUE THREAD

**Issue by OguzTNCR** [bounswe/bounswe2024group10#370]
ℹ️ Description 
* We need a page for users to see their account and information. This page has the personal info of the user as well the financial assets. This page should also have the functionality to add new assets info.

🎯 Tasks
- [ ] Create the account page.
- [ ] Show the user info like name, photo, followers, following, 
- [ ] Show user's financial assets added before.
- [ ] Show user's posts.
- [ ] Add the update account logic including the financial asset update logic.

**Comment by SturmR** [comment]
Created account page template, account page styling, the link from the search page and the styling of the link. All commits under branch lab7-account-page.
