### ISSUE TITLE
Web - Redesign Web Homepage

### ISSUE THREAD

**Issue by SturmR** [bounswe/bounswe2024group10#371]
ℹ️ Description 
* Our homepage must contain posts that are visible in their entirety. 

🎯 Tasks
- [x] Change the current format of our posts on the homepage.
- [x] Add a <...> or <Read more> when the text of the post exceeds a certain threshold of characters.
- [ ] Connect functionality of comments, likes, and dislikes and create their related buttons.

**Comment by OguzTNCR** [comment]
Comment, like, dislike functionalities are kept in the post page only. Other subtasks are done.
