### ISSUE TITLE
Planing for Second Milestone

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#377]
ℹ️ Description 
* Plan for the demo next week

🎯 Tasks
- [x] Plan the parts should be done until the second milestone.
- [x] separate responsibilities among team members.

**Comment by Pqrq** [comment]
I have created a basic user scenario, which can be used during our customer presentation

The link will be added after documenting the scenario inside our Wiki

**Comment by gulsensabak** [comment]
Since everything related to this issue is done, I am closing it right now.
