### ISSUE TITLE
Document User Experience

### ISSUE THREAD

**Issue by Pqrq** [bounswe/bounswe2024group10#378]
ℹ️ Description 
* We need to document our user experience decisions, of which were made in our previous lab. For more details, see [Link 1](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-1) and [Link 2](https://github.com/bounswe/bounswe2024group10/wiki/User-Group-Story-2)

🎯 Tasks
- [x] Document user experience decisions made in the previous lab

**Comment by OmerFarukBOUN** [comment]
Finished a long time ago
