### ISSUE TITLE
Outline the software quality plan, including unit test coverage and integration testing.

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#379]
ℹ️ Description 
* To track of the project we have to outline the software quality plan, including unit test coverage and integration testing.

🎯 Tasks
- [x] Outline the software quality plan
- [x] Outline unit test coverage and integration testing

**Comment by Pqrq** [comment]
This task has been partially done. Here are the related links for the [unit test coverage and integration testing](https://github.com/bounswe/bounswe2024group10/wiki/Milestone-2-plan)

**Comment by NazlicanAka** [comment]
We have created outlines, continuing to writing unit tests and integration tests.
