### ISSUE TITLE
Implement Like, Dislike functions on Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#382]
ℹ️ Description 
* Implement Like, Dislike functions on the posts. Use the [Like Endpoints](https://app.swaggerhub.com/apis/MESUTMELIHAKPINAR/Tradeverse/1.0.0#/Likes) and [Dislike Endpoints](https://app.swaggerhub.com/apis/MESUTMELIHAKPINAR/Tradeverse/1.0.0#/Dislikes) 

🎯 Tasks
- [x] Make like button on the postcard functional.
- [x] Make dislike button on the postcard functional.

**Comment by gulsensabak** [comment]
I have implemented like, dislike, unlike and undislike functional. I have merged the updates to mobile main. That's why, I am closing this issue right now.
