### ISSUE TITLE
Implement Follow Endpoints on Mobile

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#383]
ℹ️ Description 
* Implement Follow, Unfollow, Get Followings, Get Followers functions using the [These Endpoints](https://app.swaggerhub.com/apis/MESUTMELIHAKPINAR/Tradeverse/1.0.0#/Follow)

🎯 Tasks
- [x] Add follow user functionality.
- [x] Add unfollow user functionality.
- [x] Add functionality of getting followed users.
- [x] Add functionality of getting followers.

**Comment by gulsensabak** [comment]
All of the above functionalities connected to the backend endpoints. That's why, I am closing this issue.
