### ISSUE TITLE
Implement Search Endpoint

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#391]
ℹ️ Description 
* Create a general search endpoint with 'searchKey' or 'query' parameter. Return value should include Popular, Assets, Tags, Sub Forums, Posts and People

🎯 Tasks
- [x] Implement search endpoint.

**Comment by OmerFarukBOUN** [comment]
The search endpoint was half implemented. It will be implemented in Milestone-3

**Comment by OmerFarukBOUN** [comment]
It has been implemented
