### ISSUE TITLE
Review of scenarios and mockups

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#44]
# ℹ️ Description
* We should review the mockups and scenarios

# 🎯 Tasks
- [x] Review the scenarios
- [x] Review the mockups

**Comment by NazlicanAka** [comment]
Can you link the issue to milestone and the project, please. It is important to use them to keep track of our tasks.

**Comment by NazlicanAka** [comment]
Can you solve the problems that I have mention in [here](https://github.com/bounswe/bounswe2024group10/issues/44#issuecomment-2004723185), then close the issue, please. You have forgot to link to issue to the milestone.

**Comment by gulsensabak** [comment]
I have done it. I have moved it manually. It is under the done part for the project. When I try to add it to milestone it seems closed. Now it is open. I add it to milestone also. Please check other issues too. Thanks for your attention to my issues.
