### ISSUE TITLE
Fix portfolio endpoints

### ISSUE THREAD

**Issue by melihakpinar** [bounswe/bounswe2024group10#460]
ℹ️ Description
* Fix `/api/portfolio/get-portfolio` and `/api/portfolio/by-asset` endpoints.
* `/api/portfolio/get-portfolio` takes @RequestBody instead of @RequestParam.
* `/api/portfolio/by-asset` gets @PathVariable instead of @RequestParam.
* Convert both of these endpoints to format: `/api/portfolio/get-portfolio?username=melihakpinar` and `/api/portfolio/by-asset?assetId=3`.

🎯 Tasks
 - [x] Fix `/api/portfolio/get-portfolio`
 - [x] Fix `/api/portfolio/by-asset`
 - [x] Test in postman
 - [x] Create pull request

**Comment by NazlicanAka** [comment]
I have created the [pull request](https://github.com/bounswe/bounswe2024group10/pull/492)
