### ISSUE TITLE
Fix Non-Functional Requirements

### ISSUE THREAD

**Issue by OmerFarukBOUN** [bounswe/bounswe2024group10#48]
* Description: The non-functional requirements have not written properly. Fix it.
* Theme of the Action: Documentation
* Files to Change: None
* Estimation / Last Date: 26.03.2024 23.59

**Comment by Pqrq** [comment]
Sorry for missing the estimated deadline

Have you done anything about this issue, or if not when can we look for it?

If I woule be available, I can take a look at the non-functional requirements tonight.

Please return me asap :) , as we have our demo tomorrow.
