### ISSUE TITLE
Create Follower and Followings Screen

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#487]
On the profile page, there exists two links one of which is Followers and the other is Followings. Those screens should be navigated from the profile page and have a API connection.

Followers
- [x] Edit the existing followings screen which shows mock data so that it fetches real data.
- [x] Activate Followers option in the profile screen.
- [x] Create a followers screen applying real data fetching.
- [x] Set up a navigation from profile page to followers screen.

![Ekran Resmi 2024-12-08 21 09 59](https://github.com/user-attachments/assets/9885d133-ce9d-45fe-a6a8-d01b6db834eb)

**Comment by gulsensabak** [comment]
I have implemented all functionalities. Since there is no conflict, I have merged the related PR's. Since everyhting seems okay, I am closing this issue right now.
