### ISSUE TITLE
Create My Posts Screen

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#488]
On the profile page, there exists `My Posts` option which is disabled. It should be activated and related screen should be created.

- [x] Activate `My Posts` option in the profile screen.
![Ekran Resmi 2024-12-08 21 20 13](https://github.com/user-attachments/assets/e38d65c1-5216-4692-a8ee-5acfc30ced08)
- [x] Create a `My Posts` screen applying real data fetching.
- [x] Set up a navigation from profile page to `My Posts` screen.

**Comment by gulsensabak** [comment]
Each functionality is implemented. Since there is no conflict, I have merged the related PR. That's why, I am closing this issue right now.
