### ISSUE TITLE
Fix the image rendering problem in posts

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#505]
ℹ️ Description 
* Due to the new arrangements in backend, our old base64 version of the post's image is not working correctly. An immediate fix is needed.
🎯 Tasks
- [x] Fix the rendering retreived images in the post
- [x]  Fix the passing the image version error while creating the post.

**Comment by OguzTNCR** [comment]
After the changes in the backend the files are now kept in the storage. So we had to revise the src values of the images accordingly.
