### ISSUE TITLE
Backend Initialization

### ISSUE THREAD

**Issue by karatashsyn** [bounswe/bounswe2024group10#51]
# ℹ️ Description

The purpose of this task is to establish the foundational backend branch for our project repository and push the initial set of files necessary for starting backend development.

# 🎯 Tasks

- [x] Create the backend branch and push the initial files.

**Comment by melihakpinar** [comment]
Wrote a detailed description.

**Comment by melihakpinar** [comment]
We successfully initialized the Java Spring project and started development process.

**Comment by melihakpinar** [comment]
> I have a confusion about the issue title. Isn't it supposed to be an "initialization" issue, of if not, why does the title say so?
> 
> We can either change the contents and close this issue, or alternatively, we can change the title accordingly and keep this issue for backend tasks.
> 
> What do you think @melihakpinar @SturmR @OmerFarukBOUN @karatashsyn ?

Let’s split it

**Comment by Pqrq** [comment]
Can you open an example issue, I could not figure it out well.

**Comment by melihakpinar** [comment]
Will open all of them
