### ISSUE TITLE
Adding web mockups to scenarios

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#63]
# ℹ️ Description
* Issue Explanation: There are web mockups in the Figma page for our group. Web mockups that are appropriate for our scenarios should be added.
* Theme of the Action: Editing scenarios
* Files to Change: Scenarios

# 🎯 Tasks
* Adding the required web mockups for scenarios
- [x] scenario 1
- [x] scenario 2
- [x] scenario 3
- [x] scenario 4
- [x] scenario 5
- [x] scenario 6

# Conclusion
* will be filled

**Comment by bartukonca** [comment]
I have changed the mockups of the 1st, 2nd and 3rd scenerios to web mockups. I think the current 50/50 balance between the scenerios with mobile mockups and scenerios with web mockups is desirable so we shouldn't add web mockups to each scenerio. I will wait for your review, then we can close this issue if everything is in order.

**Comment by gulsensabak** [comment]
I think, teacher wants us to add both mobile and web mockups for all scenarios. I think we should add web mockups to all of these scenarios.

**Comment by gulsensabak** [comment]
Both of us, talked with Kutay hoca, so I add all web mockups and mobile mockups. I will close this issue after your review. @bartukonca can you review it please?

**Comment by bartukonca** [comment]
They seem great Gülşen, thank you for your help. I will close the issue now.
