### ISSUE TITLE
Connect wikidata with sql database

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#65]
# ℹ️ Description
* Issue Explanation: Make connection between wikidata with sql database(MySQL)
* Theme of the Action: Write code
* Files to Change: will be filled

# 🎯 Tasks
* Making connection between backend and database
- [ ] Write connection code

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
Today, @bartukonca wrote some queries. We can close this issue I think. @bartukonca ?

**Comment by bartukonca** [comment]
Yes the structure of the queries are clear, I will start implementing them soon. However I didn't deal with the connection itself, so we can keep the issue open for some time.

**Comment by gulsensabak** [comment]
I think we have done with all of the queries for that milestone. I think, we can close this issue. What do you think @bartukonca?

**Comment by bartukonca** [comment]
Okay then yes we can close the issue.
