### ISSUE TITLE
Do research to understand how to connect wikidata

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#66]
# ℹ️ Description
* Issue Explanation: Please read [this documentation](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/A_gentle_introduction_to_the_Wikidata_Query_Service) to understand how to get data from wikidata.
* Theme of the Action: do research
* Files to Change: will be filled

# 🎯 Tasks
* Do research how to get data from wikidata.
- [x] research for getting data

# Conclusion
* will be filled

**Comment by Pqrq** [comment]
I think this should be the task of the backend group, rather than the database group. Backend group will handle the connection between database and backend.

**Comment by gulsensabak** [comment]
Thank you @Pqrq. I have changed the description and title of the issue. Right now, it is an appropriate issue for database group.

**Comment by OmerFarukBOUN** [comment]
Nice documentation.

**Comment by bartukonca** [comment]
I read the documentation and also watched the relevant videos to better understand it.

**Comment by gulsensabak** [comment]
I have also read this documentation. It was a good starting point for SPARQL. Also, thank you my friends. I will close this issue.
