### ISSUE TITLE
Install Spring Boot

### ISSUE THREAD

**Issue by OmerFarukBOUN** [bounswe/bounswe2024group10#67]
# ℹ️ Description
* Download and install Spring Boot on your development device. You can look at this [site](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html).
* Theme of the Action: Environment Setup
* Estimation / Last Date: 21.04.2024 23:59

# 🎯 Tasks
- [x] Yusuf Kağan Çiçekdağ
- [x] Ömer Faruk Erzurumluoğlu
- [x] Melih Akpınar
- [x] Onur Kafkas

**Comment by Pqrq** [comment]
Despite the entire suffering of mine, I have finally managed to run a basic Spring Boot Application :')

As some extra tips, I am not sure but the codes provided in the -bla- site may not work properly (at least it was the case at my computer). My final working .xml and .java files with the proper file structure are as below:

pom.xml file:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>myproject</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
    </parent>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <mainClass>com.example.MyApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>


MyApplication.java file:
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@SpringBootApplication
public class MyApplication {

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }

}

File structure:
(root file, you can name it however you want)/
├── pom.xml
└── src/
    └── main/
        └── java/
            └── com/
                └── example/
                    └── MyApplication.java

Good luck :)

**Comment by SturmR** [comment]
Spring boot installation complete.
