### ISSUE TITLE
Start SQL code for the database

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#69]
# ℹ️ Description
We have completed the ER diagram for the database, coded the tables in mySQL and divided coding the relations among us.

# 🎯 Tasks
- [x] Ömer Faruk 
- [x] Gülşen Sabak
- [x] Ali Bartu Konca

**Comment by bartukonca** [comment]
I will be working on user-guest_user, blocked_user-registered_user, user-registered_user and tag-post relations

**Comment by gulsensabak** [comment]
I have added the necessary code for the relations that I have taken. @OmerFarukBOUN can you review the relations that I have created and give a comment here?

**Comment by OmerFarukBOUN** [comment]
Today, I will write my part. While I am writing I would review it

**Comment by OmerFarukBOUN** [comment]
Since we used Lucas, there were many errors in our entity plan. Me and Bartu fixed our tables. We could reopen this issue, if we need it.

**Comment by bartukonca** [comment]
I didn't directly push my own code because I did my part with the help of Ömer Faruk. He pushed both of our parts together.
