### ISSUE TITLE
Correction for the meeting notes of frontend team

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#72]
# ℹ️ Description
* We have divided our group to different subgroups. That's why, each subgroup made their own meetings. When we take notes we shouldn't put whole team to check participants if the meeting is subgroup meeting.
* Theme of the Action: changing participation part of the meeting note for frontend group
* Files to Change: meeting note

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
I will assign the frontend subgroup members. I think we should update the participants part for that [meeting note](https://github.com/bounswe/bounswe2024group10/wiki/Meeting-Notes#april-19-2024)

**Comment by TheRealLowyer** [comment]
I made the correction. Thank you for your attention Gülşen. Good work !!
