### ISSUE TITLE
Writing the sql code for relations in ER diagram

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#73]
# ℹ️ Description
* We have created the ER diagram. Also we have written the table creation codes in sql. However, we didn't write the sql code for relations between entities. We will write sql code for these relations
* Theme of the Action: write sql code
* Estimation / Last Date: 24.04.2024

# 🎯 Tasks
- [ ] Ali Bartu Konca
- [ ] Ömer Faruk Erzurumluoğlu
- [ ] Gülşen Sabak

# Conclusion
* will be filled

**Comment by bartukonca** [comment]
I have already opened an [issue](https://github.com/bounswe/bounswe2024group10/issues/69) about this, if you wish we can close this issue and continue the discussion from there.

**Comment by gulsensabak** [comment]
Oh, so sorry Bartu. It is my mistake I missed out. I am closing this issue. Thanks!
