### ISSUE TITLE
Review Database Meeting-2 Notes

### ISSUE THREAD

**Issue by bartukonca** [bounswe/bounswe2024group10#74]
# ℹ️ Description
I have uploaded the [notes](https://github.com/bounswe/bounswe2024group10/wiki/Meeting-Notes#april-21-2024) for the 2nd meeting for the database group. @gulsensabak I would greatly appreciate if you could review the notes.

# 🎯 Tasks
- [ ] Review the notes

# Conclusion
* Will be added.

**Comment by gulsensabak** [comment]
I have reviewed them. It seems perfect Thanks for your effort @bartukonca. I am closing this issue.
