### ISSUE TITLE
SQL Queries

### ISSUE THREAD

**Issue by OmerFarukBOUN** [bounswe/bounswe2024group10#89]
* There are queries to be implemented but since they are not in bulk we need to communicate needed queries within this issue. Edit this post to add new queries as tasks.  
* Theme of the Action: Query

# Queries

- [ ] Query 1
- [ ] Query 2
- [ ] Query 3

**Comment by bartukonca** [comment]
I have written some queries but I haven't fully implemented them so we can keep this issue open a bit more

**Comment by gulsensabak** [comment]
I think today, @bartukonca wrote some queries about search. We can close this issue, I think. @bartukonca what do you think?

**Comment by bartukonca** [comment]
I think we can keep it open until we fully implement all of them.

**Comment by Pqrq** [comment]
What is the current status?

Can one update the status of this issue?
