### ISSUE TITLE
Adding the meeting note for the first mobile meeting 

### ISSUE THREAD

**Issue by TheRealLowyer** [bounswe/bounswe2024group10#93]
# ℹ️ Description
* We have divided our whole team into different teams as backend, frontend and database. That's why, we attended different meetings. I will add the first meeting note for the mobile group and relevant changes in the sidebar.
* Theme of the Action: Adding meeting notes
* Files to Change: Meeting notes

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x]  Add first meeting note for mobile team
- [x] Make the necessary changes in the sidebar to the meeting note to be seen.

# Conclusion
*

**Comment by TheRealLowyer** [comment]
I added the first mobile meeting notes to the meeting notes page. I also made the relevant changes in the sidebar. Could you please review them @gulsensabak :)

**Comment by gulsensabak** [comment]
I think, you made it perfectly. Thank you my friend. I will close this issue right now.
