### ISSUE TITLE
Creating mobile pages for guest user

### ISSUE THREAD

**Issue by gulsensabak** [bounswe/bounswe2024group10#94]
# ℹ️ Description
* Since the requirements of guest user and registered user are different, I will create new pages for guest user.
* Theme of the Action: Write code
* Files to Change: 
* Estimation / Last Date: 28.04.2024

# 🎯 Tasks
* Write down the tasks and update the issue by marking them when they are done.
- [x] Home Page for guest user

# Conclusion
* will be filled

**Comment by gulsensabak** [comment]
I have created the pages for guest user. Can you review them and get feedback to me @TheRealLowyer?

**Comment by TheRealLowyer** [comment]
I have reviewes the pages. You can close this issue. Thank you @gulsensabak
