### ISSUE TITLE
Help to create a new branch and merge with main

### ISSUE THREAD

**Issue by NazlicanAka** [bounswe/bounswe2024group10#97]
# ℹ️ Description
* I have created the branch login-SignUp-pages. But I could not add my codes into it, the code in my computer. I want to add my code to the branch and create a pull request with the main. I am new in git, can you help me?

# Conclusion
* I am assigning the issue to my frontend partners to get help from them.

**Comment by melihakpinar** [comment]
```
git branch login-signup-pages
git checkout login-signup-pages
// Apply the changes here
```

Then you can see the edited files using `git status`.

- If you want to push all changed files in a single commit, you can use:

`git commit -a -m "Implement login and signup pages."`

- If you want to select some of them, you can add using:

```
git add /path/to/file/a.java
git add /path/to/file/b.java
git add /path/to/file/c/d.java
git commit -m "Implement login and signup pages."
```

(Tabii ki you can customize the commit message)

After commiting the changes, you can push them using `git push`. If you are pushing a branch for the first time you may need to use `git push --set-upstream origin <branch-name>`.

**Comment by NazlicanAka** [comment]
Thank you for your help. I have done pull request also. Can you check the changes when you have time, in case there is something else I need to do or I did something wrong?
